### ISSUE TITLE
fauna hashing

### ISSUE THREAD

**Issue by dferber90** [euroclydon37/fauna-auth#10]
I found your library by chance as I'm working on something similar.

I checked your source code and noticed that you're currently hashing the passwords yourself. You might have a good reason for it, but just in case you didn't notice it in the docs: Fauna can store the passwords separately from your user data and take care of the hashing for you. An example is shown in https://docs.fauna.com/fauna/current/tutorials/authentication/user

Feel free to just close this in case you are already aware of this stuff. I thought I'd just leave a hint here to save you some time in case you hadn't seen it yet.

**Comment by euroclydon37** [comment]
I was not aware of that. Thanks. I’ll check it out. Also not opposed to a PR. 😉

**Comment by dferber90** [comment]
I'm closing this as I only opened it as an FYI. I hope it was useful :)
